[program:aippt-sop]
process_name=%(program_name)s_%(process_num)02d
command=/www/aippt-api-server/bin/server -conf /data/wwwhome/aippt-api-server/configs
autostart=true
startsecs = 1
autorestart=true
user=root
numprocs=1
# environment=log_path="/data/logs"
redirect_stderr=true
stdout_logfile_maxbytes = 10MB
stdout_logfile_backups = 1
stdout_logfile=/data/wwwhome/aippt-api-server/supervisor.log